name: Build and cache on GitHub release

on:
  release:
    types: [published]

jobs:
  build:
    uses: dmlane/github-workflows/.github/workflows/build-and-cachix.yml@main
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

